backend:
  name: github
  repo: StartSmall/www.startsmall.co.za
  branch: master # or your default branch
media_folder: "static/images" # Folder for uploaded images
public_folder: "/images" # Public path for images
collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts" # Folder where Markdown files are stored
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }